/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package impressao3d;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Kalidsa
 */
public class jFramePaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form jFramePaginaInicial
     */
    public jFramePaginaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonConsutar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonInfos = new javax.swing.JButton();
        jLabeluser = new javax.swing.JLabel();
        jLabelArroba = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPedidos = new javax.swing.JMenu();
        jMenuRealizaPedido = new javax.swing.JMenuItem();
        jMenuConsultaPedido = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuInformacoes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Bem-vindo (a) :");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressao3d/icons/logo.png"))); // NOI18N
        jLabelLogo.setText("jLabel2");
        jLabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoMouseClicked(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressao3d/icons/touch.png"))); // NOI18N
        jButtonCadastrar.setToolTipText("Cadastrar Pedidos");
        jButtonCadastrar.setFocusable(false);
        jButtonCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastrar);

        jButtonConsutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressao3d/icons/search(1).png"))); // NOI18N
        jButtonConsutar.setToolTipText("Consultar Pedidos");
        jButtonConsutar.setFocusable(false);
        jButtonConsutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConsutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConsutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsutarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonConsutar);
        jToolBar1.add(jSeparator1);

        jButtonInfos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressao3d/icons/information.png"))); // NOI18N
        jButtonInfos.setToolTipText("Informações do Sistema");
        jButtonInfos.setFocusable(false);
        jButtonInfos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInfos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfosActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonInfos);

        jLabeluser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabelArroba.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelArroba.setText("@custom3dforgessao.png");
        jLabelArroba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArrobaMouseClicked(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuPedidos.setText("Pedidos");

        jMenuRealizaPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuRealizaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressao3d/icons/touch.png"))); // NOI18N
        jMenuRealizaPedido.setText("Cadastrar pedido");
        jMenuRealizaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRealizaPedidoActionPerformed(evt);
            }
        });
        jMenuPedidos.add(jMenuRealizaPedido);

        jMenuConsultaPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuConsultaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressao3d/icons/search(1).png"))); // NOI18N
        jMenuConsultaPedido.setText("Consultar pedidos");
        jMenuConsultaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaPedidoActionPerformed(evt);
            }
        });
        jMenuPedidos.add(jMenuConsultaPedido);

        jMenuBar1.add(jMenuPedidos);

        jMenuSobre.setText("Sobre");

        jMenuInformacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressao3d/icons/information.png"))); // NOI18N
        jMenuInformacoes.setText("Informações do Sistema");
        jMenuInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInformacoesActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuInformacoes);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabelArroba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(377, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeluser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabeluser))
                .addGap(61, 61, 61)
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelArroba)
                .addGap(176, 176, 176))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRealizaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRealizaPedidoActionPerformed
         jFrameCadastrarPedido cadastrarPedidos = new  jFrameCadastrarPedido();
        cadastrarPedidos.setVisible(true);
    }//GEN-LAST:event_jMenuRealizaPedidoActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
         jFrameCadastrarPedido cadastrarPedidos = new  jFrameCadastrarPedido();
        cadastrarPedidos.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfosActionPerformed
       JOptionPane.showMessageDialog(this, "Sistema desenvolvido para a cadeira de\nProgramação Orientada a Objetos "
               + "- Prof: Osmar\nDesenvolvedor:Anthony Souza!", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonInfosActionPerformed

    private void jMenuConsultaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaPedidoActionPerformed
        jFrameConsultarPedidos consultarPedidos = new   jFrameConsultarPedidos();
         consultarPedidos .setVisible(true);
    }//GEN-LAST:event_jMenuConsultaPedidoActionPerformed

    private void jLabelArrobaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArrobaMouseClicked
       try {
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/3d_impressao.png/"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabelArrobaMouseClicked

    private void jButtonConsutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsutarActionPerformed
         jFrameConsultarPedidos consultarPedidos = new   jFrameConsultarPedidos();
         consultarPedidos .setVisible(true);
    }//GEN-LAST:event_jButtonConsutarActionPerformed

    private void jMenuInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInformacoesActionPerformed
       JOptionPane.showMessageDialog(this, "Sistema desenvolvido para a cadeira de\nProgramação Orientada a Objetos"
               + " - Prof: Osmar\nDesenvolvedor:Anthony Souza!", "Informação", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_jMenuInformacoesActionPerformed

    private void jLabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoMouseClicked
         try {
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/3d_impressao.png/"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonConsutar;
    private javax.swing.JButton jButtonInfos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelArroba;
    private javax.swing.JLabel jLabelLogo;
    public javax.swing.JLabel jLabeluser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConsultaPedido;
    private javax.swing.JMenuItem jMenuInformacoes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuPedidos;
    private javax.swing.JMenuItem jMenuRealizaPedido;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
